name: Informationen
on: 
    pull_request:
        types: # event-type
            - opened
            - reopened
    workflow_dispatch:
    push: 
        branches: # event-filter
            - master
            - 'dev*' # der stern funktioniert im klassischem sinne einer reg
        paths:
            - '.github/workflows/*'
jobs:
    inform:
        runs-on: ubuntu-latest
        steps:
            - name: prints info
              run: echo "${{ toJSON(github.event) }}"
