name: Informationen
on: 
    pull_request:
        types:
            - opened
            - reopened
    workflow_dispatch:
    issues:
jobs:
    inform:
        runs-on: ubuntu-latest
        steps:
            - name: prints info
              run: echo "${{ toJSON(github.event) }}"
